Unit test for param files
zcash/zcash-android-wallet-sdk pull request #211
Opened 2021-01-23 23:39 UTC by herou

I wrote unit tests required from this ticket:  #202

2021-01-26 00:25 UTC, gmale commented
This looks like a good start :tada: 

From here, you probably want a setup function that runs before each unit test, that clears the param directory. Something along the lines of:

```kotlin
    @Before
    fun setup() {
        // clear the param files
        SaplingParamTool.clear(cacheDir)
    }
```
Now, each unit test is starting with an empty cache and is independent of other tests. Next, you would want to setup each test scenario:

```kotlin
    @Test
    fun testFilesExist(){
        // Given
        SaplingParamTool.fetchParams(cacheDir)
        
        // When
        val result = SaplingParamTool.validate(cacheDir)

        // Then
        Assert.assertFalse(result)
    }
 ```
 
If the `fetchParams` function works, then the previous test will succeed. So we can consider it tested. Meaning, we can build on it, as if it works, for the rest of the tests, without having to mock too much:

```kotlin
    @Test
    fun testOnlyOutputOFileExists(){
        // Given
        SaplingParamTool.fetchParams(cacheDir)
        File("$cacheDir/${ZcashSdk.SPEND_PARAM_FILE_NAME}").delete()
                
        // When
        val result = SaplingParamTool.validate(cacheDir)

        // Then
        Assert.assertFalse("Validation should fail when the spend params are missing", result)
    }
 ```

2021-01-26 00:27 UTC, gmale requested changes

2021-01-26 00:27 UTC, gmale commented on src/androidTest/java/cash/z/ecc/android/sdk/tool/SaplingParamToolTest.kt
> +    fun testOnlySpendFileExit(){
minor typo `Exit` should be `Exists`

2021-01-26 00:27 UTC, gmale commented on src/androidTest/java/cash/z/ecc/android/sdk/tool/SaplingParamToolTest.kt
> +    fun testOnlyOutputOFileExit(){
minor typo `Exit` should be `Exists`

2021-01-26 20:45 UTC, herou commented
@gmale I applied your changes above.

2021-01-27 21:49 UTC, gmale commented
Discussed over telegram the `suspend` function issues and all tests pass. Merging. 

Nice work.

From here, the next steps are on my end.

2021-01-27 21:50 UTC, merged